# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- feature/net-resources-weu

pool:
  vmImage: ubuntu-latest

variables:
    serviceConnection: 'Dev-Azure-SVC'
    terraformWorkingDirectory: 'TF-IAC'

stages:
  - stage: Dev_Plan
    displayName: 'tf_plan_dev'
    jobs:
      - job: terraformDev
        steps:
          - task: AzureCLI@2
            displayName: 'Azure_cli_login'
            inputs:
             azureSubscription: $(serviceConnection)
             scriptType: 'bash'
             scriptLocation: 'inlineScript'
             inlineScript: echo "Logged in to Azure"

          - script: |
              curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
              unzip terraform.zip
              sudo mv terraform /usr/local/bin/
              terraform -version
            displayName: 'Install Terraform'
            
          - script: terraform init
            displayName: 'terraform init'
            workingDirectory: $(terraformWorkingDirectory)
          
          - script: terraform plan -out=tfplan
            displayName: 'Terraform Plan'
            workingDirectory: $(terraformWorkingDirectory)

  - stage: Dev_Apply
    displayName: 'tf_apply_dev'
    dependsOn: Dev_Plan
    jobs:
     - job: terraformDevApply
       steps:
        - task: AzureCLI@2
          displayName: 'Azure_cli_login'
          inputs:
           azureSubscription: $(serviceConnection)
           scriptType: 'bash'
           scriptLocation: 'inlineScript'
           inlineScript: echo "Logged in to Azure"

        - script: |
              curl -sLo terraform.zip https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
              unzip terraform.zip
              sudo mv terraform /usr/local/bin/
              terraform -version
          displayName: 'Install Terraform'
        
        - script: terraform apply tfplan
          displayName: 'Terraform Apply'
          workingDirectory: $(terraformWorkingDirectory)